import type { Config } from 'tailwindcss'

export default {
  content: [
    './pages/**/*.{vue,ts}',
    './components/**/*.{vue,ts}',
    './layouts/**/*.{vue,ts}',
    './app.vue',
  ],
  theme: {
    extend: {
      colors: {
        'on-surface': '#281808',
        'surface-dim': '#f4d4bb',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#2a1800',
        'surface-tint': '#7d571e',
        'on-primary': '#ffffff',
        'primary-fixed': '#ffddb5',
        'surface-container-lowest': '#ffffff',
        'surface-container': '#ffeadb',
        error: '#ba1a1a',
        'surface-bright': '#fff8f5',
        'on-tertiary-container': '#7c4720',
        surface: '#fff8f5',
        'secondary-fixed-dim': '#ebbe90',
        'inverse-surface': '#3f2d1b',
        'surface-variant': '#fdddc3',
        'on-secondary-container': '#785731',
        'secondary-container': '#fdcf9f',
        'on-primary-fixed-variant': '#623f06',
        'on-tertiary-fixed': '#311300',
        background: '#fff8f5',
        'surface-container-low': '#fff1e8',
        outline: '#817568',
        'secondary-fixed': '#ffddbb',
        'surface-container-highest': '#fdddc3',
        'tertiary-container': '#ffba8e',
        primary: '#7d571e',
        'on-error-container': '#93000a',
        'on-error': '#ffffff',
        'inverse-primary': '#f1bd7b',
        'error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#6c3a14',
        'on-background': '#281808',
        'on-secondary': '#ffffff',
        secondary: '#795832',
        tertiary: '#885129',
        'on-primary-container': '#724d14',
        'on-secondary-fixed-variant': '#5f401c',
        'tertiary-fixed-dim': '#ffb787',
        'primary-fixed-dim': '#f1bd7b',
        'tertiary-fixed': '#ffdcc7',
        'inverse-on-surface': '#ffeee1',
        'primary-container': '#f4c07d',
        'on-surface-variant': '#4f4539',
        'on-secondary-fixed': '#2b1700',
        'surface-container-high': '#ffe3cd',
        'outline-variant': '#d3c4b4',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        xl: '80px',
        lg: '48px',
        xs: '4px',
        sm: '12px',
        md: '24px',
        base: '8px',
      },
      fontFamily: {
        jakarta: ['Plus Jakarta Sans', 'sans-serif'],
        vietnam: ['Be Vietnam Pro', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        h3: ['24px', { lineHeight: '1.4', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        h1: ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
        h2: ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
} satisfies Config
