# ---- Build stage ----
FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o werawoof-api ./cmd/main.go

# ---- Run stage ----
FROM alpine:3.20

WORKDIR /app

COPY --from=builder /app/werawoof-api .

EXPOSE 8080

CMD ["./werawoof-api"]
